services:
    web:
        build: ./web
        pull_policy: build
        restart: unless-stopped
        container_name: web
        volumes:
            - /home/syntarex/web:/usr/src/app
    nginx:
        build: ./nginx
        pull_policy: build
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80/tcp
    palworld:
        image: thijsvanloef/palworld-server-docker
        pull_policy: always
        restart: unless-stopped
        container_name: palworld
        volumes:
            - /home/syntarex/palworld:/palworld
        ports:
            - 8211:8211/udp
            - 27015:27015/udp
            - 25575:25575/tcp
        environment:
            - PORT=8211
            - PLAYERS=16
            - MULTITHREADING=true
            - COMMUNITY=false
