services:
    database:
        image: postgres
        pull_policy: always
        shm_size: 128mb # Beschränke Speichernutzung
        restart: unless-stopped
        container_name: database
        volumes:
            - ./database/data:/var/lib/postgresql/data
        ports:
            - 5432:5432/tcp
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]

    web:
        build:
            context: ./
            dockerfile: ./web/Dockerfile
        depends_on:
            database:
                condition: service_healthy
        pull_policy: build
        restart: unless-stopped
        container_name: web
        healthcheck:
            test: "curl -f localhost:3000"

    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            web:
                condition: service_healthy
        pull_policy: build
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp

    palworld:
        image: thijsvanloef/palworld-server-docker
        pull_policy: always
        restart: unless-stopped
        container_name: palworld
        volumes:
            - ./palworld:/palworld
        ports:
            - 8211:8211/udp
            - 27015:27015/udp
            - 25575:25575/tcp
        environment:
            - PORT=8211
            - MULTITHREADING=true
            - COMMUNITY=${PALWORLD_COMMUNITY}
            - AUTO_UPDATE_ENABLED=true
            - DISABLE_GENERATE_SETTINGS=true
            - DELETE_OLD_BACKUPS=true
            - OLD_BACKUP_DAYS=7
