services:
    database:
        image: postgres
        pull_policy: always
        shm_size: 128mb # Beschränke Speichernutzung
        restart: unless-stopped
        container_name: database
        volumes:
            - ./database/data:/var/lib/postgresql/data
        ports:
            - 5432:5432/tcp
        environment:
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        healthcheck:
            test: ["CMD-SHELL", "pg_isready"]

    palworld:
        image: thijsvanloef/palworld-server-docker
        pull_policy: always
        restart: unless-stopped
        container_name: palworld
        volumes:
            - ./palworld:/palworld
        ports:
            - ${PALWORLD_PORT}:${PALWORLD_PORT}/udp
            - 27015:27015/udp
            - 25575:25575/tcp
        environment:
            - PORT=${PALWORLD_PORT}
            - MULTITHREADING=true
            - COMMUNITY=${PALWORLD_COMMUNITY}
            - ADMIN_PASSWORD=${PALWORLD_ADMIN_PASSWORD}
            - AUTO_UPDATE_ENABLED=true
            - DISABLE_GENERATE_SETTINGS=true
            - DELETE_OLD_BACKUPS=true
            - OLD_BACKUP_DAYS=7
            - RCON_ENABLED=true
            - RCON_PORT=25575

    clonehero:
        build:
            context: ./
            dockerfile: ./clonehero/Dockerfile
        pull_policy: always
        restart: unless-stopped
        container_name: clonehero
        ports:
            - 14242:14242/udp

    web:
        build:
            context: ./
            dockerfile: ./web/Dockerfile
        depends_on:
            database:
                condition: service_healthy
            palworld:
                condition: service_healthy
        pull_policy: build
        restart: unless-stopped
        container_name: web
        ports:
            - 3000:3000/tcp
        healthcheck:
            test: "curl -f web:3000"

    nginx:
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        depends_on:
            web:
                condition: service_healthy
        pull_policy: build
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp
