services:
    env:
        env_file:
            - path: ./.env
              required: true
            - path: ./.env.production
              required: true
        build:
            context: ./

    web:
        extends: env
        build:
            context: ./
            dockerfile: ./web/Dockerfile
        pull_policy: build
        restart: unless-stopped
        container_name: web

    nginx:
        extends: env
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        pull_policy: build
        restart: unless-stopped
        container_name: nginx
        ports:
            - 80:80/tcp
            - 443:443/tcp

    palworld:
        extends: env
        image: thijsvanloef/palworld-server-docker
        pull_policy: always
        restart: unless-stopped
        container_name: palworld

        volumes:
            - ./palworld:/palworld
        ports:
            - 8211:8211/udp
            - 27015:27015/udp
            - 25575:25575/tcp
        environment:
            - PORT=8211
            - MULTITHREADING=true
            - COMMUNITY=${PALWORLD_COMMUNITY}
            - AUTO_UPDATE_ENABLED=true
            - DISABLE_GENERATE_SETTINGS=true
            - DELETE_OLD_BACKUPS=true
            - OLD_BACKUP_DAYS=7
