FROM nginx:alpine

# Lösche existierende Konfigurationen
RUN rm /etc/nginx/conf.d/*

# Kopiere Konfiguration
COPY ../nginx/default.conf /etc/nginx/conf.d/

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
